/* data_block.c generated by valac 0.16.1, the Vala compiler
 * generated from data_block.vala, do not modify */

/*

  This file is part of VoxelPress.

  VoxelPress is free software: you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  VoxelPress is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with VoxelPress.  If not, see <http://www.gnu.org/licenses/>.

  Have a nice day!

*/

#include <glib.h>
#include <glib-object.h>


#define LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND (libvoxelcore_voxel_model_data_block_kind_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND, libvoxelcorevoxel_modelDataBlockKind))
#define LIBVOXELCORE_VOXEL_MODEL_IS_DATA_BLOCK_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND))
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND, libvoxelcorevoxel_modelDataBlockKindIface))

typedef struct _libvoxelcorevoxel_modelDataBlockKind libvoxelcorevoxel_modelDataBlockKind;
typedef struct _libvoxelcorevoxel_modelDataBlockKindIface libvoxelcorevoxel_modelDataBlockKindIface;

#define LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND (libvoxelcore_voxel_model_voxel_kind_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND, libvoxelcorevoxel_modelVoxelKind))
#define LIBVOXELCORE_VOXEL_MODEL_IS_VOXEL_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND))
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND, libvoxelcorevoxel_modelVoxelKindIface))

typedef struct _libvoxelcorevoxel_modelVoxelKind libvoxelcorevoxel_modelVoxelKind;
typedef struct _libvoxelcorevoxel_modelVoxelKindIface libvoxelcorevoxel_modelVoxelKindIface;

#define LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND (libvoxelcore_materials_material_kind_get_type ())
#define LIBVOXELCORE_MATERIALS_MATERIAL_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND, libvoxelcorematerialsMaterialKind))
#define LIBVOXELCORE_MATERIALS_IS_MATERIAL_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND))
#define LIBVOXELCORE_MATERIALS_MATERIAL_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND, libvoxelcorematerialsMaterialKindIface))

typedef struct _libvoxelcorematerialsMaterialKind libvoxelcorematerialsMaterialKind;
typedef struct _libvoxelcorematerialsMaterialKindIface libvoxelcorematerialsMaterialKindIface;

#define LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK (libvoxelcore_voxel_model_data_block_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK, libvoxelcorevoxel_modelDataBlock))
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK, libvoxelcorevoxel_modelDataBlockClass))
#define LIBVOXELCORE_VOXEL_MODEL_IS_DATA_BLOCK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK))
#define LIBVOXELCORE_VOXEL_MODEL_IS_DATA_BLOCK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK))
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK, libvoxelcorevoxel_modelDataBlockClass))

typedef struct _libvoxelcorevoxel_modelDataBlock libvoxelcorevoxel_modelDataBlock;
typedef struct _libvoxelcorevoxel_modelDataBlockClass libvoxelcorevoxel_modelDataBlockClass;
typedef struct _libvoxelcorevoxel_modelDataBlockPrivate libvoxelcorevoxel_modelDataBlockPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _libvoxelcorematerialsMaterialKindIface {
	GTypeInterface parent_iface;
};

struct _libvoxelcorevoxel_modelVoxelKindIface {
	GTypeInterface parent_iface;
	libvoxelcorematerialsMaterialKind* (*get_material) (libvoxelcorevoxel_modelVoxelKind* self);
	void (*set_material) (libvoxelcorevoxel_modelVoxelKind* self, libvoxelcorematerialsMaterialKind* value);
};

struct _libvoxelcorevoxel_modelDataBlockKindIface {
	GTypeInterface parent_iface;
	libvoxelcorevoxel_modelVoxelKind* (*get) (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y);
	void (*set) (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* voxel);
};

struct _libvoxelcorevoxel_modelDataBlock {
	GObject parent_instance;
	libvoxelcorevoxel_modelDataBlockPrivate * priv;
};

struct _libvoxelcorevoxel_modelDataBlockClass {
	GObjectClass parent_class;
};

struct _libvoxelcorevoxel_modelDataBlockPrivate {
	libvoxelcorevoxel_modelVoxelKind** _data;
	gint _data_length1;
	gint _data_length2;
};


static gpointer libvoxelcore_voxel_model_data_block_parent_class = NULL;
static libvoxelcorevoxel_modelDataBlockKindIface* libvoxelcore_voxel_model_data_block_libvoxelcore_voxel_model_data_block_kind_parent_iface = NULL;

GType libvoxelcore_materials_material_kind_get_type (void) G_GNUC_CONST;
GType libvoxelcore_voxel_model_voxel_kind_get_type (void) G_GNUC_CONST;
GType libvoxelcore_voxel_model_data_block_kind_get_type (void) G_GNUC_CONST;
GType libvoxelcore_voxel_model_data_block_get_type (void) G_GNUC_CONST;
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK, libvoxelcorevoxel_modelDataBlockPrivate))
enum  {
	LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_DUMMY_PROPERTY
};
libvoxelcorevoxel_modelDataBlock* libvoxelcore_voxel_model_data_block_new (gint block_size);
libvoxelcorevoxel_modelDataBlock* libvoxelcore_voxel_model_data_block_construct (GType object_type, gint block_size);
static void libvoxelcore_voxel_model_data_block_set_data (libvoxelcorevoxel_modelDataBlock* self, libvoxelcorevoxel_modelVoxelKind** value, int value_length1, int value_length2);
static libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_data_block_real_get (libvoxelcorevoxel_modelDataBlockKind* base, gint x, gint y);
libvoxelcorevoxel_modelVoxelKind** libvoxelcore_voxel_model_data_block_get_data (libvoxelcorevoxel_modelDataBlock* self, int* result_length1, int* result_length2);
static void libvoxelcore_voxel_model_data_block_real_set (libvoxelcorevoxel_modelDataBlockKind* base, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* vox);
static libvoxelcorevoxel_modelVoxelKind** _vala_array_dup2 (libvoxelcorevoxel_modelVoxelKind** self, int length);
static void libvoxelcore_voxel_model_data_block_finalize (GObject* obj);
static void _vala_libvoxelcore_voxel_model_data_block_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_libvoxelcore_voxel_model_data_block_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


libvoxelcorevoxel_modelDataBlock* libvoxelcore_voxel_model_data_block_construct (GType object_type, gint block_size) {
	libvoxelcorevoxel_modelDataBlock * self = NULL;
	gint _tmp0_;
	gint _tmp1_;
	libvoxelcorevoxel_modelVoxelKind** _tmp2_ = NULL;
	libvoxelcorevoxel_modelVoxelKind** _tmp3_;
	gint _tmp3__length1;
	gint _tmp3__length2;
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	self = (libvoxelcorevoxel_modelDataBlock*) g_object_new (object_type, NULL);
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp0_ = block_size;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1_ = block_size;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp2_ = g_new0 (libvoxelcorevoxel_modelVoxelKind*, (_tmp0_ * _tmp1_) + 1);
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp3_ = _tmp2_;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp3__length1 = _tmp0_;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp3__length2 = _tmp1_;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	libvoxelcore_voxel_model_data_block_set_data (self, _tmp3_, _tmp0_, _tmp1_);
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp3_ = (_vala_array_free (_tmp3_, _tmp3__length1 * _tmp3__length2, (GDestroyNotify) g_object_unref), NULL);
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	return self;
#line 151 "data_block.c"
}


libvoxelcorevoxel_modelDataBlock* libvoxelcore_voxel_model_data_block_new (gint block_size) {
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	return libvoxelcore_voxel_model_data_block_construct (LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK, block_size);
#line 158 "data_block.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	return self ? g_object_ref (self) : NULL;
#line 165 "data_block.c"
}


static libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_data_block_real_get (libvoxelcorevoxel_modelDataBlockKind* base, gint x, gint y) {
	libvoxelcorevoxel_modelDataBlock * self;
	libvoxelcorevoxel_modelVoxelKind* result = NULL;
	libvoxelcorevoxel_modelVoxelKind** _tmp0_;
	gint _tmp0__length1;
	gint _tmp0__length2;
	libvoxelcorevoxel_modelVoxelKind** _tmp1_;
	gint _tmp1__length1;
	gint _tmp1__length2;
	gint _tmp2_;
	gint _tmp3_;
	libvoxelcorevoxel_modelVoxelKind* _tmp4_;
	libvoxelcorevoxel_modelVoxelKind* _tmp5_;
#line 31 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	self = (libvoxelcorevoxel_modelDataBlock*) base;
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp0_ = libvoxelcore_voxel_model_data_block_get_data (self, &_tmp0__length1, &_tmp0__length2);
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1_ = _tmp0_;
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1__length1 = _tmp0__length1;
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1__length2 = _tmp0__length2;
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp2_ = x;
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp3_ = y;
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp4_ = _tmp1_[(_tmp2_ * _tmp1__length2) + _tmp3_];
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	result = _tmp5_;
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	return result;
#line 204 "data_block.c"
}


static void libvoxelcore_voxel_model_data_block_real_set (libvoxelcorevoxel_modelDataBlockKind* base, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* vox) {
	libvoxelcorevoxel_modelDataBlock * self;
	libvoxelcorevoxel_modelVoxelKind** _tmp0_;
	gint _tmp0__length1;
	gint _tmp0__length2;
	libvoxelcorevoxel_modelVoxelKind** _tmp1_;
	gint _tmp1__length1;
	gint _tmp1__length2;
	gint _tmp2_;
	gint _tmp3_;
	libvoxelcorevoxel_modelVoxelKind* _tmp4_;
	libvoxelcorevoxel_modelVoxelKind* _tmp5_;
	libvoxelcorevoxel_modelVoxelKind* _tmp6_;
#line 35 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	self = (libvoxelcorevoxel_modelDataBlock*) base;
#line 35 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	g_return_if_fail (vox != NULL);
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp0_ = libvoxelcore_voxel_model_data_block_get_data (self, &_tmp0__length1, &_tmp0__length2);
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1_ = _tmp0_;
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1__length1 = _tmp0__length1;
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1__length2 = _tmp0__length2;
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp2_ = x;
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp3_ = y;
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp4_ = vox;
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_g_object_unref0 (_tmp1_[(_tmp2_ * _tmp1__length2) + _tmp3_]);
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1_[(_tmp2_ * _tmp1__length2) + _tmp3_] = _tmp5_;
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp6_ = _tmp1_[(_tmp2_ * _tmp1__length2) + _tmp3_];
#line 247 "data_block.c"
}


libvoxelcorevoxel_modelVoxelKind** libvoxelcore_voxel_model_data_block_get_data (libvoxelcorevoxel_modelDataBlock* self, int* result_length1, int* result_length2) {
	libvoxelcorevoxel_modelVoxelKind** result;
	libvoxelcorevoxel_modelVoxelKind** _tmp0_;
	gint _tmp0__length1;
	gint _tmp0__length2;
	libvoxelcorevoxel_modelVoxelKind** _tmp1_;
	gint _tmp1__length1;
	gint _tmp1__length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp0_ = self->priv->_data;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp0__length1 = self->priv->_data_length1;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp0__length2 = self->priv->_data_length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1_ = _tmp0_;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1__length1 = _tmp0__length1;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1__length2 = _tmp0__length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	if (result_length1) {
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
		*result_length1 = _tmp1__length1;
#line 277 "data_block.c"
	}
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	if (result_length2) {
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
		*result_length2 = _tmp1__length2;
#line 283 "data_block.c"
	}
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	result = _tmp1_;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	return result;
#line 289 "data_block.c"
}


static libvoxelcorevoxel_modelVoxelKind** _vala_array_dup2 (libvoxelcorevoxel_modelVoxelKind** self, int length) {
	libvoxelcorevoxel_modelVoxelKind** result;
	int i;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	result = g_new0 (libvoxelcorevoxel_modelVoxelKind*, length + 1);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	for (i = 0; i < length; i++) {
#line 300 "data_block.c"
		libvoxelcorevoxel_modelVoxelKind* _tmp0_;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
		_tmp0_ = _g_object_ref0 (self[i]);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
		result[i] = _tmp0_;
#line 306 "data_block.c"
	}
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	return result;
#line 310 "data_block.c"
}


static void libvoxelcore_voxel_model_data_block_set_data (libvoxelcorevoxel_modelDataBlock* self, libvoxelcorevoxel_modelVoxelKind** value, int value_length1, int value_length2) {
	libvoxelcorevoxel_modelVoxelKind** _tmp0_;
	gint _tmp0__length1;
	gint _tmp0__length2;
	libvoxelcorevoxel_modelVoxelKind** _tmp1_;
	gint _tmp1__length1;
	gint _tmp1__length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	g_return_if_fail (self != NULL);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp0_ = value;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp0__length1 = value_length1;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp0__length2 = value_length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup2 (_tmp0_, _tmp0__length1 * _tmp0__length2) : ((gpointer) _tmp0_);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1__length1 = _tmp0__length1;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	_tmp1__length2 = _tmp0__length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	self->priv->_data = (_vala_array_free (self->priv->_data, self->priv->_data_length1 * self->priv->_data_length2, (GDestroyNotify) g_object_unref), NULL);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	self->priv->_data = _tmp1_;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	self->priv->_data_length1 = _tmp1__length1;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	self->priv->_data_length2 = _tmp1__length2;
#line 343 "data_block.c"
}


static void libvoxelcore_voxel_model_data_block_class_init (libvoxelcorevoxel_modelDataBlockClass * klass) {
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	libvoxelcore_voxel_model_data_block_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	g_type_class_add_private (klass, sizeof (libvoxelcorevoxel_modelDataBlockPrivate));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_libvoxelcore_voxel_model_data_block_get_property;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_libvoxelcore_voxel_model_data_block_set_property;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	G_OBJECT_CLASS (klass)->finalize = libvoxelcore_voxel_model_data_block_finalize;
#line 358 "data_block.c"
}


static void libvoxelcore_voxel_model_data_block_libvoxelcore_voxel_model_data_block_kind_interface_init (libvoxelcorevoxel_modelDataBlockKindIface * iface) {
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	libvoxelcore_voxel_model_data_block_libvoxelcore_voxel_model_data_block_kind_parent_iface = g_type_interface_peek_parent (iface);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	iface->get = (libvoxelcorevoxel_modelVoxelKind* (*)(libvoxelcorevoxel_modelDataBlockKind*, gint, gint)) libvoxelcore_voxel_model_data_block_real_get;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	iface->set = (void (*)(libvoxelcorevoxel_modelDataBlockKind*, gint, gint, libvoxelcorevoxel_modelVoxelKind*)) libvoxelcore_voxel_model_data_block_real_set;
#line 369 "data_block.c"
}


static void libvoxelcore_voxel_model_data_block_instance_init (libvoxelcorevoxel_modelDataBlock * self) {
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	self->priv = LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_GET_PRIVATE (self);
#line 376 "data_block.c"
}


static void libvoxelcore_voxel_model_data_block_finalize (GObject* obj) {
	libvoxelcorevoxel_modelDataBlock * self;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	self = LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK (obj);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	self->priv->_data = (_vala_array_free (self->priv->_data, self->priv->_data_length1 * self->priv->_data_length2, (GDestroyNotify) g_object_unref), NULL);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	G_OBJECT_CLASS (libvoxelcore_voxel_model_data_block_parent_class)->finalize (obj);
#line 388 "data_block.c"
}


GType libvoxelcore_voxel_model_data_block_get_type (void) {
	static volatile gsize libvoxelcore_voxel_model_data_block_type_id__volatile = 0;
	if (g_once_init_enter (&libvoxelcore_voxel_model_data_block_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (libvoxelcorevoxel_modelDataBlockClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) libvoxelcore_voxel_model_data_block_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (libvoxelcorevoxel_modelDataBlock), 0, (GInstanceInitFunc) libvoxelcore_voxel_model_data_block_instance_init, NULL };
		static const GInterfaceInfo libvoxelcore_voxel_model_data_block_kind_info = { (GInterfaceInitFunc) libvoxelcore_voxel_model_data_block_libvoxelcore_voxel_model_data_block_kind_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType libvoxelcore_voxel_model_data_block_type_id;
		libvoxelcore_voxel_model_data_block_type_id = g_type_register_static (G_TYPE_OBJECT, "libvoxelcorevoxel_modelDataBlock", &g_define_type_info, 0);
		g_type_add_interface_static (libvoxelcore_voxel_model_data_block_type_id, LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND, &libvoxelcore_voxel_model_data_block_kind_info);
		g_once_init_leave (&libvoxelcore_voxel_model_data_block_type_id__volatile, libvoxelcore_voxel_model_data_block_type_id);
	}
	return libvoxelcore_voxel_model_data_block_type_id__volatile;
}


static void _vala_libvoxelcore_voxel_model_data_block_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	libvoxelcorevoxel_modelDataBlock * self;
	self = LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK (object);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	switch (property_id) {
#line 411 "data_block.c"
		default:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
		break;
#line 417 "data_block.c"
	}
}


static void _vala_libvoxelcore_voxel_model_data_block_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	libvoxelcorevoxel_modelDataBlock * self;
	self = LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK (object);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
	switch (property_id) {
#line 427 "data_block.c"
		default:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/data_block.vala"
		break;
#line 433 "data_block.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



