/* interfaces.c generated by valac 0.16.1, the Vala compiler
 * generated from interfaces.vala, do not modify */

/*

  This file is part of VoxelPress.

  VoxelPress is free software: you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  VoxelPress is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with VoxelPress.  If not, see <http://www.gnu.org/licenses/>.

  Have a nice day!

*/

#include <glib.h>
#include <glib-object.h>


#define LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND (libvoxelcore_voxel_model_voxel_kind_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND, libvoxelcorevoxel_modelVoxelKind))
#define LIBVOXELCORE_VOXEL_MODEL_IS_VOXEL_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND))
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND, libvoxelcorevoxel_modelVoxelKindIface))

typedef struct _libvoxelcorevoxel_modelVoxelKind libvoxelcorevoxel_modelVoxelKind;
typedef struct _libvoxelcorevoxel_modelVoxelKindIface libvoxelcorevoxel_modelVoxelKindIface;

#define LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND (libvoxelcore_materials_material_kind_get_type ())
#define LIBVOXELCORE_MATERIALS_MATERIAL_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND, libvoxelcorematerialsMaterialKind))
#define LIBVOXELCORE_MATERIALS_IS_MATERIAL_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND))
#define LIBVOXELCORE_MATERIALS_MATERIAL_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND, libvoxelcorematerialsMaterialKindIface))

typedef struct _libvoxelcorematerialsMaterialKind libvoxelcorematerialsMaterialKind;
typedef struct _libvoxelcorematerialsMaterialKindIface libvoxelcorematerialsMaterialKindIface;

#define LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_MODEL_KIND (libvoxelcore_voxel_model_voxel_model_kind_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_MODEL_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_MODEL_KIND, libvoxelcorevoxel_modelVoxelModelKind))
#define LIBVOXELCORE_VOXEL_MODEL_IS_VOXEL_MODEL_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_MODEL_KIND))
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_MODEL_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_MODEL_KIND, libvoxelcorevoxel_modelVoxelModelKindIface))

typedef struct _libvoxelcorevoxel_modelVoxelModelKind libvoxelcorevoxel_modelVoxelModelKind;
typedef struct _libvoxelcorevoxel_modelVoxelModelKindIface libvoxelcorevoxel_modelVoxelModelKindIface;

#define LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER_KIND (libvoxelcore_voxel_model_raster_layer_kind_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER_KIND, libvoxelcorevoxel_modelRasterLayerKind))
#define LIBVOXELCORE_VOXEL_MODEL_IS_RASTER_LAYER_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER_KIND))
#define LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER_KIND, libvoxelcorevoxel_modelRasterLayerKindIface))

typedef struct _libvoxelcorevoxel_modelRasterLayerKind libvoxelcorevoxel_modelRasterLayerKind;
typedef struct _libvoxelcorevoxel_modelRasterLayerKindIface libvoxelcorevoxel_modelRasterLayerKindIface;

#define LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND (libvoxelcore_voxel_model_data_block_kind_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND, libvoxelcorevoxel_modelDataBlockKind))
#define LIBVOXELCORE_VOXEL_MODEL_IS_DATA_BLOCK_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND))
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND, libvoxelcorevoxel_modelDataBlockKindIface))

typedef struct _libvoxelcorevoxel_modelDataBlockKind libvoxelcorevoxel_modelDataBlockKind;
typedef struct _libvoxelcorevoxel_modelDataBlockKindIface libvoxelcorevoxel_modelDataBlockKindIface;

struct _libvoxelcorematerialsMaterialKindIface {
	GTypeInterface parent_iface;
};

struct _libvoxelcorevoxel_modelVoxelKindIface {
	GTypeInterface parent_iface;
	libvoxelcorematerialsMaterialKind* (*get_material) (libvoxelcorevoxel_modelVoxelKind* self);
	void (*set_material) (libvoxelcorevoxel_modelVoxelKind* self, libvoxelcorematerialsMaterialKind* value);
};

struct _libvoxelcorevoxel_modelVoxelModelKindIface {
	GTypeInterface parent_iface;
	libvoxelcorevoxel_modelVoxelKind* (*get) (libvoxelcorevoxel_modelVoxelModelKind* self, gint x, gint y, gint z);
	void (*set) (libvoxelcorevoxel_modelVoxelModelKind* self, gint x, gint y, gint z, libvoxelcorevoxel_modelVoxelKind* voxel);
};

struct _libvoxelcorevoxel_modelRasterLayerKindIface {
	GTypeInterface parent_iface;
	libvoxelcorevoxel_modelVoxelKind* (*get) (libvoxelcorevoxel_modelRasterLayerKind* self, gint x, gint y);
	void (*set) (libvoxelcorevoxel_modelRasterLayerKind* self, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* voxel);
};

struct _libvoxelcorevoxel_modelDataBlockKindIface {
	GTypeInterface parent_iface;
	libvoxelcorevoxel_modelVoxelKind* (*get) (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y);
	void (*set) (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* voxel);
};



GType libvoxelcore_materials_material_kind_get_type (void) G_GNUC_CONST;
GType libvoxelcore_voxel_model_voxel_kind_get_type (void) G_GNUC_CONST;
libvoxelcorematerialsMaterialKind* libvoxelcore_voxel_model_voxel_kind_get_material (libvoxelcorevoxel_modelVoxelKind* self);
void libvoxelcore_voxel_model_voxel_kind_set_material (libvoxelcorevoxel_modelVoxelKind* self, libvoxelcorematerialsMaterialKind* value);
GType libvoxelcore_voxel_model_voxel_model_kind_get_type (void) G_GNUC_CONST;
libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_voxel_model_kind_get (libvoxelcorevoxel_modelVoxelModelKind* self, gint x, gint y, gint z);
void libvoxelcore_voxel_model_voxel_model_kind_set (libvoxelcorevoxel_modelVoxelModelKind* self, gint x, gint y, gint z, libvoxelcorevoxel_modelVoxelKind* voxel);
GType libvoxelcore_voxel_model_raster_layer_kind_get_type (void) G_GNUC_CONST;
libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_raster_layer_kind_get (libvoxelcorevoxel_modelRasterLayerKind* self, gint x, gint y);
void libvoxelcore_voxel_model_raster_layer_kind_set (libvoxelcorevoxel_modelRasterLayerKind* self, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* voxel);
GType libvoxelcore_voxel_model_data_block_kind_get_type (void) G_GNUC_CONST;
libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_data_block_kind_get (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y);
void libvoxelcore_voxel_model_data_block_kind_set (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* voxel);


libvoxelcorematerialsMaterialKind* libvoxelcore_voxel_model_voxel_kind_get_material (libvoxelcorevoxel_modelVoxelKind* self) {
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	return LIBVOXELCORE_VOXEL_MODEL_VOXEL_KIND_GET_INTERFACE (self)->get_material (self);
#line 120 "interfaces.c"
}


void libvoxelcore_voxel_model_voxel_kind_set_material (libvoxelcorevoxel_modelVoxelKind* self, libvoxelcorematerialsMaterialKind* value) {
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	g_return_if_fail (self != NULL);
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	LIBVOXELCORE_VOXEL_MODEL_VOXEL_KIND_GET_INTERFACE (self)->set_material (self, value);
#line 129 "interfaces.c"
}


static void libvoxelcore_voxel_model_voxel_kind_base_init (libvoxelcorevoxel_modelVoxelKindIface * iface) {
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	static gboolean initialized = FALSE;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	if (!initialized) {
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
		initialized = TRUE;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
		g_object_interface_install_property (iface, g_param_spec_object ("material", "material", "material", LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 142 "interfaces.c"
	}
}


GType libvoxelcore_voxel_model_voxel_kind_get_type (void) {
	static volatile gsize libvoxelcore_voxel_model_voxel_kind_type_id__volatile = 0;
	if (g_once_init_enter (&libvoxelcore_voxel_model_voxel_kind_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (libvoxelcorevoxel_modelVoxelKindIface), (GBaseInitFunc) libvoxelcore_voxel_model_voxel_kind_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType libvoxelcore_voxel_model_voxel_kind_type_id;
		libvoxelcore_voxel_model_voxel_kind_type_id = g_type_register_static (G_TYPE_INTERFACE, "libvoxelcorevoxel_modelVoxelKind", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (libvoxelcore_voxel_model_voxel_kind_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&libvoxelcore_voxel_model_voxel_kind_type_id__volatile, libvoxelcore_voxel_model_voxel_kind_type_id);
	}
	return libvoxelcore_voxel_model_voxel_kind_type_id__volatile;
}


libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_voxel_model_kind_get (libvoxelcorevoxel_modelVoxelModelKind* self, gint x, gint y, gint z) {
#line 52 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 52 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	return LIBVOXELCORE_VOXEL_MODEL_VOXEL_MODEL_KIND_GET_INTERFACE (self)->get (self, x, y, z);
#line 165 "interfaces.c"
}


void libvoxelcore_voxel_model_voxel_model_kind_set (libvoxelcorevoxel_modelVoxelModelKind* self, gint x, gint y, gint z, libvoxelcorevoxel_modelVoxelKind* voxel) {
#line 53 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	g_return_if_fail (self != NULL);
#line 53 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	LIBVOXELCORE_VOXEL_MODEL_VOXEL_MODEL_KIND_GET_INTERFACE (self)->set (self, x, y, z, voxel);
#line 174 "interfaces.c"
}


static void libvoxelcore_voxel_model_voxel_model_kind_base_init (libvoxelcorevoxel_modelVoxelModelKindIface * iface) {
#line 34 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	static gboolean initialized = FALSE;
#line 34 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	if (!initialized) {
#line 34 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
		initialized = TRUE;
#line 185 "interfaces.c"
	}
}


GType libvoxelcore_voxel_model_voxel_model_kind_get_type (void) {
	static volatile gsize libvoxelcore_voxel_model_voxel_model_kind_type_id__volatile = 0;
	if (g_once_init_enter (&libvoxelcore_voxel_model_voxel_model_kind_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (libvoxelcorevoxel_modelVoxelModelKindIface), (GBaseInitFunc) libvoxelcore_voxel_model_voxel_model_kind_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType libvoxelcore_voxel_model_voxel_model_kind_type_id;
		libvoxelcore_voxel_model_voxel_model_kind_type_id = g_type_register_static (G_TYPE_INTERFACE, "libvoxelcorevoxel_modelVoxelModelKind", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (libvoxelcore_voxel_model_voxel_model_kind_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&libvoxelcore_voxel_model_voxel_model_kind_type_id__volatile, libvoxelcore_voxel_model_voxel_model_kind_type_id);
	}
	return libvoxelcore_voxel_model_voxel_model_kind_type_id__volatile;
}


libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_raster_layer_kind_get (libvoxelcorevoxel_modelRasterLayerKind* self, gint x, gint y) {
#line 58 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 58 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	return LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_KIND_GET_INTERFACE (self)->get (self, x, y);
#line 208 "interfaces.c"
}


void libvoxelcore_voxel_model_raster_layer_kind_set (libvoxelcorevoxel_modelRasterLayerKind* self, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* voxel) {
#line 59 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	g_return_if_fail (self != NULL);
#line 59 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_KIND_GET_INTERFACE (self)->set (self, x, y, voxel);
#line 217 "interfaces.c"
}


static void libvoxelcore_voxel_model_raster_layer_kind_base_init (libvoxelcorevoxel_modelRasterLayerKindIface * iface) {
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	static gboolean initialized = FALSE;
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	if (!initialized) {
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
		initialized = TRUE;
#line 228 "interfaces.c"
	}
}


GType libvoxelcore_voxel_model_raster_layer_kind_get_type (void) {
	static volatile gsize libvoxelcore_voxel_model_raster_layer_kind_type_id__volatile = 0;
	if (g_once_init_enter (&libvoxelcore_voxel_model_raster_layer_kind_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (libvoxelcorevoxel_modelRasterLayerKindIface), (GBaseInitFunc) libvoxelcore_voxel_model_raster_layer_kind_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType libvoxelcore_voxel_model_raster_layer_kind_type_id;
		libvoxelcore_voxel_model_raster_layer_kind_type_id = g_type_register_static (G_TYPE_INTERFACE, "libvoxelcorevoxel_modelRasterLayerKind", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (libvoxelcore_voxel_model_raster_layer_kind_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&libvoxelcore_voxel_model_raster_layer_kind_type_id__volatile, libvoxelcore_voxel_model_raster_layer_kind_type_id);
	}
	return libvoxelcore_voxel_model_raster_layer_kind_type_id__volatile;
}


libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_data_block_kind_get (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y) {
#line 64 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 64 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	return LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_KIND_GET_INTERFACE (self)->get (self, x, y);
#line 251 "interfaces.c"
}


void libvoxelcore_voxel_model_data_block_kind_set (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* voxel) {
#line 65 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	g_return_if_fail (self != NULL);
#line 65 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_KIND_GET_INTERFACE (self)->set (self, x, y, voxel);
#line 260 "interfaces.c"
}


static void libvoxelcore_voxel_model_data_block_kind_base_init (libvoxelcorevoxel_modelDataBlockKindIface * iface) {
#line 63 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	static gboolean initialized = FALSE;
#line 63 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
	if (!initialized) {
#line 63 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/interfaces.vala"
		initialized = TRUE;
#line 271 "interfaces.c"
	}
}


GType libvoxelcore_voxel_model_data_block_kind_get_type (void) {
	static volatile gsize libvoxelcore_voxel_model_data_block_kind_type_id__volatile = 0;
	if (g_once_init_enter (&libvoxelcore_voxel_model_data_block_kind_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (libvoxelcorevoxel_modelDataBlockKindIface), (GBaseInitFunc) libvoxelcore_voxel_model_data_block_kind_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType libvoxelcore_voxel_model_data_block_kind_type_id;
		libvoxelcore_voxel_model_data_block_kind_type_id = g_type_register_static (G_TYPE_INTERFACE, "libvoxelcorevoxel_modelDataBlockKind", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (libvoxelcore_voxel_model_data_block_kind_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&libvoxelcore_voxel_model_data_block_kind_type_id__volatile, libvoxelcore_voxel_model_data_block_kind_type_id);
	}
	return libvoxelcore_voxel_model_data_block_kind_type_id__volatile;
}



