/* raster_layer.c generated by valac 0.16.1, the Vala compiler
 * generated from raster_layer.vala, do not modify */

/*

  This file is part of VoxelPress.

  VoxelPress is free software: you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  VoxelPress is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with VoxelPress.  If not, see <http://www.gnu.org/licenses/>.

  Have a nice day!

*/

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>


#define LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER_KIND (libvoxelcore_voxel_model_raster_layer_kind_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER_KIND, libvoxelcorevoxel_modelRasterLayerKind))
#define LIBVOXELCORE_VOXEL_MODEL_IS_RASTER_LAYER_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER_KIND))
#define LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER_KIND, libvoxelcorevoxel_modelRasterLayerKindIface))

typedef struct _libvoxelcorevoxel_modelRasterLayerKind libvoxelcorevoxel_modelRasterLayerKind;
typedef struct _libvoxelcorevoxel_modelRasterLayerKindIface libvoxelcorevoxel_modelRasterLayerKindIface;

#define LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND (libvoxelcore_voxel_model_voxel_kind_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND, libvoxelcorevoxel_modelVoxelKind))
#define LIBVOXELCORE_VOXEL_MODEL_IS_VOXEL_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND))
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND, libvoxelcorevoxel_modelVoxelKindIface))

typedef struct _libvoxelcorevoxel_modelVoxelKind libvoxelcorevoxel_modelVoxelKind;
typedef struct _libvoxelcorevoxel_modelVoxelKindIface libvoxelcorevoxel_modelVoxelKindIface;

#define LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND (libvoxelcore_materials_material_kind_get_type ())
#define LIBVOXELCORE_MATERIALS_MATERIAL_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND, libvoxelcorematerialsMaterialKind))
#define LIBVOXELCORE_MATERIALS_IS_MATERIAL_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND))
#define LIBVOXELCORE_MATERIALS_MATERIAL_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND, libvoxelcorematerialsMaterialKindIface))

typedef struct _libvoxelcorematerialsMaterialKind libvoxelcorematerialsMaterialKind;
typedef struct _libvoxelcorematerialsMaterialKindIface libvoxelcorematerialsMaterialKindIface;

#define LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER (libvoxelcore_voxel_model_raster_layer_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER, libvoxelcorevoxel_modelRasterLayer))
#define LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER, libvoxelcorevoxel_modelRasterLayerClass))
#define LIBVOXELCORE_VOXEL_MODEL_IS_RASTER_LAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER))
#define LIBVOXELCORE_VOXEL_MODEL_IS_RASTER_LAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER))
#define LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER, libvoxelcorevoxel_modelRasterLayerClass))

typedef struct _libvoxelcorevoxel_modelRasterLayer libvoxelcorevoxel_modelRasterLayer;
typedef struct _libvoxelcorevoxel_modelRasterLayerClass libvoxelcorevoxel_modelRasterLayerClass;
typedef struct _libvoxelcorevoxel_modelRasterLayerPrivate libvoxelcorevoxel_modelRasterLayerPrivate;

#define LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND (libvoxelcore_voxel_model_data_block_kind_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND, libvoxelcorevoxel_modelDataBlockKind))
#define LIBVOXELCORE_VOXEL_MODEL_IS_DATA_BLOCK_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND))
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK_KIND, libvoxelcorevoxel_modelDataBlockKindIface))

typedef struct _libvoxelcorevoxel_modelDataBlockKind libvoxelcorevoxel_modelDataBlockKind;
typedef struct _libvoxelcorevoxel_modelDataBlockKindIface libvoxelcorevoxel_modelDataBlockKindIface;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK (libvoxelcore_voxel_model_data_block_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK, libvoxelcorevoxel_modelDataBlock))
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK, libvoxelcorevoxel_modelDataBlockClass))
#define LIBVOXELCORE_VOXEL_MODEL_IS_DATA_BLOCK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK))
#define LIBVOXELCORE_VOXEL_MODEL_IS_DATA_BLOCK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK))
#define LIBVOXELCORE_VOXEL_MODEL_DATA_BLOCK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_DATA_BLOCK, libvoxelcorevoxel_modelDataBlockClass))

typedef struct _libvoxelcorevoxel_modelDataBlock libvoxelcorevoxel_modelDataBlock;
typedef struct _libvoxelcorevoxel_modelDataBlockClass libvoxelcorevoxel_modelDataBlockClass;

struct _libvoxelcorematerialsMaterialKindIface {
	GTypeInterface parent_iface;
};

struct _libvoxelcorevoxel_modelVoxelKindIface {
	GTypeInterface parent_iface;
	libvoxelcorematerialsMaterialKind* (*get_material) (libvoxelcorevoxel_modelVoxelKind* self);
	void (*set_material) (libvoxelcorevoxel_modelVoxelKind* self, libvoxelcorematerialsMaterialKind* value);
};

struct _libvoxelcorevoxel_modelRasterLayerKindIface {
	GTypeInterface parent_iface;
	libvoxelcorevoxel_modelVoxelKind* (*get) (libvoxelcorevoxel_modelRasterLayerKind* self, gint x, gint y);
	void (*set) (libvoxelcorevoxel_modelRasterLayerKind* self, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* voxel);
};

struct _libvoxelcorevoxel_modelRasterLayer {
	GObject parent_instance;
	libvoxelcorevoxel_modelRasterLayerPrivate * priv;
};

struct _libvoxelcorevoxel_modelRasterLayerClass {
	GObjectClass parent_class;
};

struct _libvoxelcorevoxel_modelDataBlockKindIface {
	GTypeInterface parent_iface;
	libvoxelcorevoxel_modelVoxelKind* (*get) (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y);
	void (*set) (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* voxel);
};

struct _libvoxelcorevoxel_modelRasterLayerPrivate {
	libvoxelcorevoxel_modelDataBlockKind** _blocks;
	gint _blocks_length1;
	gint _blocks_length2;
	gint _center_x;
	gint _center_y;
	gint _width;
	gint _length;
	gint _block_size;
	GStaticRecMutex __lock_blocks;
};


static gpointer libvoxelcore_voxel_model_raster_layer_parent_class = NULL;
static libvoxelcorevoxel_modelRasterLayerKindIface* libvoxelcore_voxel_model_raster_layer_libvoxelcore_voxel_model_raster_layer_kind_parent_iface = NULL;

GType libvoxelcore_materials_material_kind_get_type (void) G_GNUC_CONST;
GType libvoxelcore_voxel_model_voxel_kind_get_type (void) G_GNUC_CONST;
GType libvoxelcore_voxel_model_raster_layer_kind_get_type (void) G_GNUC_CONST;
GType libvoxelcore_voxel_model_raster_layer_get_type (void) G_GNUC_CONST;
GType libvoxelcore_voxel_model_data_block_kind_get_type (void) G_GNUC_CONST;
#define LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER, libvoxelcorevoxel_modelRasterLayerPrivate))
enum  {
	LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_DUMMY_PROPERTY,
	LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_CENTER_X,
	LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_CENTER_Y,
	LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_WIDTH,
	LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_LENGTH,
	LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_BLOCK_SIZE
};
libvoxelcorevoxel_modelRasterLayer* libvoxelcore_voxel_model_raster_layer_new (gint block_size, gint layer_width, gint layer_length);
libvoxelcorevoxel_modelRasterLayer* libvoxelcore_voxel_model_raster_layer_construct (GType object_type, gint block_size, gint layer_width, gint layer_length);
static void libvoxelcore_voxel_model_raster_layer_set_block_size (libvoxelcorevoxel_modelRasterLayer* self, gint value);
static void libvoxelcore_voxel_model_raster_layer_set_width (libvoxelcorevoxel_modelRasterLayer* self, gint value);
static void libvoxelcore_voxel_model_raster_layer_set_length (libvoxelcorevoxel_modelRasterLayer* self, gint value);
gint libvoxelcore_voxel_model_raster_layer_get_width (libvoxelcorevoxel_modelRasterLayer* self);
static void libvoxelcore_voxel_model_raster_layer_set_center_x (libvoxelcorevoxel_modelRasterLayer* self, gint value);
gint libvoxelcore_voxel_model_raster_layer_get_length (libvoxelcorevoxel_modelRasterLayer* self);
static void libvoxelcore_voxel_model_raster_layer_set_center_y (libvoxelcorevoxel_modelRasterLayer* self, gint value);
static void libvoxelcore_voxel_model_raster_layer_set_blocks (libvoxelcorevoxel_modelRasterLayer* self, libvoxelcorevoxel_modelDataBlockKind** value, int value_length1, int value_length2);
gboolean libvoxelcore_voxel_model_raster_layer_in_boundary (libvoxelcorevoxel_modelRasterLayer* self, gint local_x, gint local_y);
static libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_raster_layer_real_get (libvoxelcorevoxel_modelRasterLayerKind* base, gint x, gint y);
gint libvoxelcore_voxel_model_raster_layer_get_center_x (libvoxelcorevoxel_modelRasterLayer* self);
gint libvoxelcore_voxel_model_raster_layer_get_center_y (libvoxelcorevoxel_modelRasterLayer* self);
libvoxelcorevoxel_modelDataBlockKind** libvoxelcore_voxel_model_raster_layer_get_blocks (libvoxelcorevoxel_modelRasterLayer* self, int* result_length1, int* result_length2);
gint libvoxelcore_voxel_model_raster_layer_get_block_size (libvoxelcorevoxel_modelRasterLayer* self);
libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_data_block_kind_get (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y);
static void libvoxelcore_voxel_model_raster_layer_real_set (libvoxelcorevoxel_modelRasterLayerKind* base, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* vox);
libvoxelcorevoxel_modelDataBlock* libvoxelcore_voxel_model_data_block_new (gint block_size);
libvoxelcorevoxel_modelDataBlock* libvoxelcore_voxel_model_data_block_construct (GType object_type, gint block_size);
GType libvoxelcore_voxel_model_data_block_get_type (void) G_GNUC_CONST;
void libvoxelcore_voxel_model_data_block_kind_set (libvoxelcorevoxel_modelDataBlockKind* self, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* voxel);
static libvoxelcorevoxel_modelDataBlockKind** _vala_array_dup1 (libvoxelcorevoxel_modelDataBlockKind** self, int length);
static void libvoxelcore_voxel_model_raster_layer_finalize (GObject* obj);
static void _vala_libvoxelcore_voxel_model_raster_layer_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_libvoxelcore_voxel_model_raster_layer_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


libvoxelcorevoxel_modelRasterLayer* libvoxelcore_voxel_model_raster_layer_construct (GType object_type, gint block_size, gint layer_width, gint layer_length) {
	libvoxelcorevoxel_modelRasterLayer * self = NULL;
	gint _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	gdouble tmp_x;
	gint _tmp7_;
	gint _tmp8_;
	gdouble tmp_y;
	gdouble _tmp9_ = 0.0;
	gint x_ct;
	gdouble _tmp10_ = 0.0;
	gint y_ct;
	libvoxelcorevoxel_modelDataBlockKind** _tmp11_ = NULL;
	libvoxelcorevoxel_modelDataBlockKind** _tmp12_;
	gint _tmp12__length1;
	gint _tmp12__length2;
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self = (libvoxelcorevoxel_modelRasterLayer*) g_object_new (object_type, NULL);
#line 33 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = block_size;
#line 33 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	libvoxelcore_voxel_model_raster_layer_set_block_size (self, _tmp0_);
#line 34 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp1_ = layer_width;
#line 34 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	libvoxelcore_voxel_model_raster_layer_set_width (self, _tmp1_);
#line 35 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp2_ = layer_length;
#line 35 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	libvoxelcore_voxel_model_raster_layer_set_length (self, _tmp2_);
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp3_ = self->priv->_width;
#line 36 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	libvoxelcore_voxel_model_raster_layer_set_center_x (self, _tmp3_ / 2);
#line 37 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp4_ = self->priv->_length;
#line 37 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	libvoxelcore_voxel_model_raster_layer_set_center_y (self, _tmp4_ / 2);
#line 38 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp5_ = layer_width;
#line 38 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp6_ = block_size;
#line 38 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	tmp_x = ((gdouble) _tmp5_) / ((gdouble) _tmp6_);
#line 39 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp7_ = layer_length;
#line 39 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp8_ = block_size;
#line 39 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	tmp_y = ((gdouble) _tmp7_) / ((gdouble) _tmp8_);
#line 40 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp9_ = ceil (tmp_x);
#line 40 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	x_ct = (gint) _tmp9_;
#line 41 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp10_ = ceil (tmp_y);
#line 41 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	y_ct = (gint) _tmp10_;
#line 42 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp11_ = g_new0 (libvoxelcorevoxel_modelDataBlockKind*, (x_ct * y_ct) + 1);
#line 42 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp12_ = _tmp11_;
#line 42 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp12__length1 = x_ct;
#line 42 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp12__length2 = y_ct;
#line 42 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	libvoxelcore_voxel_model_raster_layer_set_blocks (self, _tmp12_, x_ct, y_ct);
#line 42 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp12_ = (_vala_array_free (_tmp12_, _tmp12__length1 * _tmp12__length2, (GDestroyNotify) g_object_unref), NULL);
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return self;
#line 254 "raster_layer.c"
}


libvoxelcorevoxel_modelRasterLayer* libvoxelcore_voxel_model_raster_layer_new (gint block_size, gint layer_width, gint layer_length) {
#line 32 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return libvoxelcore_voxel_model_raster_layer_construct (LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER, block_size, layer_width, layer_length);
#line 261 "raster_layer.c"
}


gboolean libvoxelcore_voxel_model_raster_layer_in_boundary (libvoxelcorevoxel_modelRasterLayer* self, gint local_x, gint local_y) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gint _tmp3_;
	gboolean _tmp5_;
	gboolean _tmp8_;
	gboolean _tmp11_;
#line 45 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp3_ = local_x;
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	if (_tmp3_ >= 0) {
#line 280 "raster_layer.c"
		gint _tmp4_;
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp4_ = local_y;
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp2_ = _tmp4_ >= 0;
#line 286 "raster_layer.c"
	} else {
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp2_ = FALSE;
#line 290 "raster_layer.c"
	}
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp5_ = _tmp2_;
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	if (_tmp5_) {
#line 296 "raster_layer.c"
		gint _tmp6_;
		gint _tmp7_;
#line 48 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp6_ = local_x;
#line 48 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp7_ = self->priv->_width;
#line 48 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp1_ = _tmp6_ < _tmp7_;
#line 305 "raster_layer.c"
	} else {
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp1_ = FALSE;
#line 309 "raster_layer.c"
	}
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp8_ = _tmp1_;
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	if (_tmp8_) {
#line 315 "raster_layer.c"
		gint _tmp9_;
		gint _tmp10_;
#line 48 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp9_ = local_y;
#line 48 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp10_ = self->priv->_length;
#line 48 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp0_ = _tmp9_ < _tmp10_;
#line 324 "raster_layer.c"
	} else {
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp0_ = FALSE;
#line 328 "raster_layer.c"
	}
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp11_ = _tmp0_;
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	result = _tmp11_;
#line 47 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return result;
#line 336 "raster_layer.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return self ? g_object_ref (self) : NULL;
#line 343 "raster_layer.c"
}


static libvoxelcorevoxel_modelVoxelKind* libvoxelcore_voxel_model_raster_layer_real_get (libvoxelcorevoxel_modelRasterLayerKind* base, gint x, gint y) {
	libvoxelcorevoxel_modelRasterLayer * self;
	libvoxelcorevoxel_modelVoxelKind* result = NULL;
	gint _tmp0_;
	gint _tmp1_;
	gint local_x;
	gint _tmp2_;
	gint _tmp3_;
	gint local_y;
	libvoxelcorevoxel_modelVoxelKind* ret;
	gint _tmp4_;
	gint _tmp5_;
	gboolean _tmp6_ = FALSE;
#line 51 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self = (libvoxelcorevoxel_modelRasterLayer*) base;
#line 52 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = self->priv->_center_x;
#line 52 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp1_ = x;
#line 52 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	local_x = _tmp0_ + _tmp1_;
#line 53 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp2_ = self->priv->_center_y;
#line 53 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp3_ = y;
#line 53 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	local_y = _tmp2_ + _tmp3_;
#line 54 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	ret = NULL;
#line 56 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp4_ = local_x;
#line 56 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp5_ = local_y;
#line 56 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp6_ = libvoxelcore_voxel_model_raster_layer_in_boundary (self, _tmp4_, _tmp5_);
#line 56 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	if (_tmp6_) {
#line 384 "raster_layer.c"
		libvoxelcorevoxel_modelDataBlockKind** _tmp7_;
		gint _tmp7__length1;
		gint _tmp7__length2;
		libvoxelcorevoxel_modelDataBlockKind** _tmp8_;
		gint _tmp8__length1;
		gint _tmp8__length2;
		gint _tmp9_;
		gint _tmp10_;
		gint _tmp11_;
		gint _tmp12_;
		libvoxelcorevoxel_modelDataBlockKind* _tmp13_;
		libvoxelcorevoxel_modelDataBlockKind* _tmp14_;
		libvoxelcorevoxel_modelDataBlockKind* block;
		libvoxelcorevoxel_modelDataBlockKind* _tmp15_;
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp7_ = libvoxelcore_voxel_model_raster_layer_get_blocks (self, &_tmp7__length1, &_tmp7__length2);
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp8_ = _tmp7_;
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp8__length1 = _tmp7__length1;
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp8__length2 = _tmp7__length2;
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp9_ = local_x;
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp10_ = self->priv->_block_size;
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp11_ = local_y;
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp12_ = self->priv->_block_size;
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp13_ = _tmp8_[((_tmp9_ / _tmp10_) * _tmp8__length2) + (_tmp11_ / _tmp12_)];
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp14_ = _g_object_ref0 (_tmp13_);
#line 57 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		block = _tmp14_;
#line 58 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp15_ = block;
#line 58 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		if (_tmp15_ != NULL) {
#line 425 "raster_layer.c"
			libvoxelcorevoxel_modelDataBlockKind* _tmp16_;
			gint _tmp17_;
			gint _tmp18_;
			gint _tmp19_;
			gint _tmp20_;
			libvoxelcorevoxel_modelVoxelKind* _tmp21_ = NULL;
#line 59 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_tmp16_ = block;
#line 59 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_tmp17_ = local_x;
#line 59 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_tmp18_ = self->priv->_block_size;
#line 59 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_tmp19_ = local_y;
#line 59 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_tmp20_ = self->priv->_block_size;
#line 59 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_tmp21_ = libvoxelcore_voxel_model_data_block_kind_get (_tmp16_, _tmp17_ % _tmp18_, _tmp19_ % _tmp20_);
#line 59 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_g_object_unref0 (ret);
#line 59 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			ret = _tmp21_;
#line 448 "raster_layer.c"
		}
#line 56 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_g_object_unref0 (block);
#line 452 "raster_layer.c"
	}
#line 63 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	result = ret;
#line 63 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return result;
#line 458 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_real_set (libvoxelcorevoxel_modelRasterLayerKind* base, gint x, gint y, libvoxelcorevoxel_modelVoxelKind* vox) {
	libvoxelcorevoxel_modelRasterLayer * self;
	gint _tmp0_;
	gint _tmp1_;
	gint local_x;
	gint _tmp2_;
	gint _tmp3_;
	gint local_y;
	gint _tmp4_;
	gint _tmp5_;
	gboolean _tmp6_ = FALSE;
	GError * _inner_error_ = NULL;
#line 66 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self = (libvoxelcorevoxel_modelRasterLayer*) base;
#line 66 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_if_fail (vox != NULL);
#line 67 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = self->priv->_center_x;
#line 67 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp1_ = x;
#line 67 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	local_x = _tmp0_ + _tmp1_;
#line 68 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp2_ = self->priv->_center_y;
#line 68 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp3_ = y;
#line 68 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	local_y = _tmp2_ + _tmp3_;
#line 69 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp4_ = local_x;
#line 69 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp5_ = local_y;
#line 69 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp6_ = libvoxelcore_voxel_model_raster_layer_in_boundary (self, _tmp4_, _tmp5_);
#line 69 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	if (_tmp6_) {
#line 498 "raster_layer.c"
		gint _tmp7_;
		gint _tmp8_;
		gint block_x;
		gint _tmp9_;
		gint _tmp10_;
		gint block_y;
#line 70 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp7_ = local_x;
#line 70 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp8_ = self->priv->_block_size;
#line 70 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		block_x = _tmp7_ / _tmp8_;
#line 71 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp9_ = local_y;
#line 71 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp10_ = self->priv->_block_size;
#line 71 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		block_y = _tmp9_ / _tmp10_;
#line 517 "raster_layer.c"
		{
			libvoxelcorevoxel_modelDataBlockKind** _tmp11_;
			gint _tmp11__length1;
			gint _tmp11__length2;
			libvoxelcorevoxel_modelDataBlockKind** _tmp12_;
			gint _tmp12__length1;
			gint _tmp12__length2;
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_tmp11_ = libvoxelcore_voxel_model_raster_layer_get_blocks (self, &_tmp11__length1, &_tmp11__length2);
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_tmp12_ = _tmp11_;
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_tmp12__length1 = _tmp11__length1;
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			_tmp12__length2 = _tmp11__length2;
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			g_static_rec_mutex_lock (&self->priv->__lock_blocks);
#line 535 "raster_layer.c"
			{
				libvoxelcorevoxel_modelDataBlockKind** _tmp13_;
				gint _tmp13__length1;
				gint _tmp13__length2;
				libvoxelcorevoxel_modelDataBlockKind** _tmp14_;
				gint _tmp14__length1;
				gint _tmp14__length2;
				gint _tmp15_;
				gint _tmp16_;
				libvoxelcorevoxel_modelDataBlockKind* _tmp17_;
				libvoxelcorevoxel_modelDataBlockKind* _tmp18_;
				libvoxelcorevoxel_modelDataBlockKind* block;
				libvoxelcorevoxel_modelDataBlockKind* _tmp19_;
				libvoxelcorevoxel_modelDataBlockKind* _tmp29_;
				gint _tmp30_;
				gint _tmp31_;
				gint _tmp32_;
				gint _tmp33_;
				libvoxelcorevoxel_modelVoxelKind* _tmp34_;
#line 74 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp13_ = libvoxelcore_voxel_model_raster_layer_get_blocks (self, &_tmp13__length1, &_tmp13__length2);
#line 74 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp14_ = _tmp13_;
#line 74 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp14__length1 = _tmp13__length1;
#line 74 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp14__length2 = _tmp13__length2;
#line 74 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp15_ = block_x;
#line 74 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp16_ = block_y;
#line 74 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp17_ = _tmp14_[(_tmp15_ * _tmp14__length2) + _tmp16_];
#line 74 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp18_ = _g_object_ref0 (_tmp17_);
#line 74 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				block = _tmp18_;
#line 75 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp19_ = block;
#line 75 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				if (_tmp19_ == NULL) {
#line 577 "raster_layer.c"
					gint _tmp20_;
					libvoxelcorevoxel_modelDataBlock* _tmp21_;
					libvoxelcorevoxel_modelDataBlockKind** _tmp22_;
					gint _tmp22__length1;
					gint _tmp22__length2;
					libvoxelcorevoxel_modelDataBlockKind** _tmp23_;
					gint _tmp23__length1;
					gint _tmp23__length2;
					gint _tmp24_;
					gint _tmp25_;
					libvoxelcorevoxel_modelDataBlockKind* _tmp26_;
					libvoxelcorevoxel_modelDataBlockKind* _tmp27_;
					libvoxelcorevoxel_modelDataBlockKind* _tmp28_;
#line 76 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp20_ = self->priv->_block_size;
#line 76 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp21_ = libvoxelcore_voxel_model_data_block_new (_tmp20_);
#line 76 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_g_object_unref0 (block);
#line 76 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					block = (libvoxelcorevoxel_modelDataBlockKind*) _tmp21_;
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp22_ = libvoxelcore_voxel_model_raster_layer_get_blocks (self, &_tmp22__length1, &_tmp22__length2);
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp23_ = _tmp22_;
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp23__length1 = _tmp22__length1;
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp23__length2 = _tmp22__length2;
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp24_ = block_x;
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp25_ = block_y;
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp26_ = block;
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp27_ = _g_object_ref0 (_tmp26_);
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_g_object_unref0 (_tmp23_[(_tmp24_ * _tmp23__length2) + _tmp25_]);
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp23_[(_tmp24_ * _tmp23__length2) + _tmp25_] = _tmp27_;
#line 77 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
					_tmp28_ = _tmp23_[(_tmp24_ * _tmp23__length2) + _tmp25_];
#line 621 "raster_layer.c"
				}
#line 79 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp29_ = block;
#line 79 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp30_ = local_x;
#line 79 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp31_ = self->priv->_block_size;
#line 79 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp32_ = local_y;
#line 79 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp33_ = self->priv->_block_size;
#line 79 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp34_ = vox;
#line 79 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				libvoxelcore_voxel_model_data_block_kind_set (_tmp29_, _tmp30_ % _tmp31_, _tmp32_ % _tmp33_, _tmp34_);
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_g_object_unref0 (block);
#line 639 "raster_layer.c"
			}
			__finally0:
			{
				libvoxelcorevoxel_modelDataBlockKind** _tmp35_;
				gint _tmp35__length1;
				gint _tmp35__length2;
				libvoxelcorevoxel_modelDataBlockKind** _tmp36_;
				gint _tmp36__length1;
				gint _tmp36__length2;
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp35_ = libvoxelcore_voxel_model_raster_layer_get_blocks (self, &_tmp35__length1, &_tmp35__length2);
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp36_ = _tmp35_;
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp36__length1 = _tmp35__length1;
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				_tmp36__length2 = _tmp35__length2;
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				g_static_rec_mutex_unlock (&self->priv->__lock_blocks);
#line 659 "raster_layer.c"
			}
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
			if (_inner_error_ != NULL) {
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				g_clear_error (&_inner_error_);
#line 73 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
				return;
#line 669 "raster_layer.c"
			}
		}
	}
}


libvoxelcorevoxel_modelDataBlockKind** libvoxelcore_voxel_model_raster_layer_get_blocks (libvoxelcorevoxel_modelRasterLayer* self, int* result_length1, int* result_length2) {
	libvoxelcorevoxel_modelDataBlockKind** result;
	libvoxelcorevoxel_modelDataBlockKind** _tmp0_;
	gint _tmp0__length1;
	gint _tmp0__length2;
	libvoxelcorevoxel_modelDataBlockKind** _tmp1_;
	gint _tmp1__length1;
	gint _tmp1__length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = self->priv->_blocks;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0__length1 = self->priv->_blocks_length1;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0__length2 = self->priv->_blocks_length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp1_ = _tmp0_;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp1__length1 = _tmp0__length1;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp1__length2 = _tmp0__length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	if (result_length1) {
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		*result_length1 = _tmp1__length1;
#line 702 "raster_layer.c"
	}
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	if (result_length2) {
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		*result_length2 = _tmp1__length2;
#line 708 "raster_layer.c"
	}
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	result = _tmp1_;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return result;
#line 714 "raster_layer.c"
}


static libvoxelcorevoxel_modelDataBlockKind** _vala_array_dup1 (libvoxelcorevoxel_modelDataBlockKind** self, int length) {
	libvoxelcorevoxel_modelDataBlockKind** result;
	int i;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	result = g_new0 (libvoxelcorevoxel_modelDataBlockKind*, length + 1);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	for (i = 0; i < length; i++) {
#line 725 "raster_layer.c"
		libvoxelcorevoxel_modelDataBlockKind* _tmp0_;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		_tmp0_ = _g_object_ref0 (self[i]);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		result[i] = _tmp0_;
#line 731 "raster_layer.c"
	}
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return result;
#line 735 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_set_blocks (libvoxelcorevoxel_modelRasterLayer* self, libvoxelcorevoxel_modelDataBlockKind** value, int value_length1, int value_length2) {
	libvoxelcorevoxel_modelDataBlockKind** _tmp0_;
	gint _tmp0__length1;
	gint _tmp0__length2;
	libvoxelcorevoxel_modelDataBlockKind** _tmp1_;
	gint _tmp1__length1;
	gint _tmp1__length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_if_fail (self != NULL);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = value;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0__length1 = value_length1;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0__length2 = value_length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup1 (_tmp0_, _tmp0__length1 * _tmp0__length2) : ((gpointer) _tmp0_);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp1__length1 = _tmp0__length1;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp1__length2 = _tmp0__length2;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv->_blocks = (_vala_array_free (self->priv->_blocks, self->priv->_blocks_length1 * self->priv->_blocks_length2, (GDestroyNotify) g_object_unref), NULL);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv->_blocks = _tmp1_;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv->_blocks_length1 = _tmp1__length1;
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv->_blocks_length2 = _tmp1__length2;
#line 768 "raster_layer.c"
}


gint libvoxelcore_voxel_model_raster_layer_get_center_x (libvoxelcorevoxel_modelRasterLayer* self) {
	gint result;
	gint _tmp0_;
#line 26 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 26 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = self->priv->_center_x;
#line 26 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	result = _tmp0_;
#line 26 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return result;
#line 783 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_set_center_x (libvoxelcorevoxel_modelRasterLayer* self, gint value) {
	gint _tmp0_;
#line 26 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_if_fail (self != NULL);
#line 26 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = value;
#line 26 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv->_center_x = _tmp0_;
#line 26 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_object_notify ((GObject *) self, "center-x");
#line 797 "raster_layer.c"
}


gint libvoxelcore_voxel_model_raster_layer_get_center_y (libvoxelcorevoxel_modelRasterLayer* self) {
	gint result;
	gint _tmp0_;
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = self->priv->_center_y;
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	result = _tmp0_;
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return result;
#line 812 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_set_center_y (libvoxelcorevoxel_modelRasterLayer* self, gint value) {
	gint _tmp0_;
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_if_fail (self != NULL);
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = value;
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv->_center_y = _tmp0_;
#line 27 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_object_notify ((GObject *) self, "center-y");
#line 826 "raster_layer.c"
}


gint libvoxelcore_voxel_model_raster_layer_get_width (libvoxelcorevoxel_modelRasterLayer* self) {
	gint result;
	gint _tmp0_;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = self->priv->_width;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	result = _tmp0_;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return result;
#line 841 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_set_width (libvoxelcorevoxel_modelRasterLayer* self, gint value) {
	gint _tmp0_;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_if_fail (self != NULL);
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = value;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv->_width = _tmp0_;
#line 28 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_object_notify ((GObject *) self, "width");
#line 855 "raster_layer.c"
}


gint libvoxelcore_voxel_model_raster_layer_get_length (libvoxelcorevoxel_modelRasterLayer* self) {
	gint result;
	gint _tmp0_;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = self->priv->_length;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	result = _tmp0_;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return result;
#line 870 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_set_length (libvoxelcorevoxel_modelRasterLayer* self, gint value) {
	gint _tmp0_;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_if_fail (self != NULL);
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = value;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv->_length = _tmp0_;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_object_notify ((GObject *) self, "length");
#line 884 "raster_layer.c"
}


gint libvoxelcore_voxel_model_raster_layer_get_block_size (libvoxelcorevoxel_modelRasterLayer* self) {
	gint result;
	gint _tmp0_;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = self->priv->_block_size;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	result = _tmp0_;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	return result;
#line 899 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_set_block_size (libvoxelcorevoxel_modelRasterLayer* self, gint value) {
	gint _tmp0_;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_return_if_fail (self != NULL);
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	_tmp0_ = value;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv->_block_size = _tmp0_;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_object_notify ((GObject *) self, "block-size");
#line 913 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_class_init (libvoxelcorevoxel_modelRasterLayerClass * klass) {
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	libvoxelcore_voxel_model_raster_layer_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_type_class_add_private (klass, sizeof (libvoxelcorevoxel_modelRasterLayerPrivate));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_libvoxelcore_voxel_model_raster_layer_get_property;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_libvoxelcore_voxel_model_raster_layer_set_property;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	G_OBJECT_CLASS (klass)->finalize = libvoxelcore_voxel_model_raster_layer_finalize;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_CENTER_X, g_param_spec_int ("center-x", "center-x", "center-x", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_CENTER_Y, g_param_spec_int ("center-y", "center-y", "center-y", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_WIDTH, g_param_spec_int ("width", "width", "width", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_LENGTH, g_param_spec_int ("length", "length", "length", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_BLOCK_SIZE, g_param_spec_int ("block-size", "block-size", "block-size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
#line 938 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_libvoxelcore_voxel_model_raster_layer_kind_interface_init (libvoxelcorevoxel_modelRasterLayerKindIface * iface) {
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	libvoxelcore_voxel_model_raster_layer_libvoxelcore_voxel_model_raster_layer_kind_parent_iface = g_type_interface_peek_parent (iface);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	iface->get = (libvoxelcorevoxel_modelVoxelKind* (*)(libvoxelcorevoxel_modelRasterLayerKind*, gint, gint)) libvoxelcore_voxel_model_raster_layer_real_get;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	iface->set = (void (*)(libvoxelcorevoxel_modelRasterLayerKind*, gint, gint, libvoxelcorevoxel_modelVoxelKind*)) libvoxelcore_voxel_model_raster_layer_real_set;
#line 949 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_instance_init (libvoxelcorevoxel_modelRasterLayer * self) {
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv = LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_GET_PRIVATE (self);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_static_rec_mutex_init (&self->priv->__lock_blocks);
#line 958 "raster_layer.c"
}


static void libvoxelcore_voxel_model_raster_layer_finalize (GObject* obj) {
	libvoxelcorevoxel_modelRasterLayer * self;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self = LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER (obj);
#line 25 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	self->priv->_blocks = (_vala_array_free (self->priv->_blocks, self->priv->_blocks_length1 * self->priv->_blocks_length2, (GDestroyNotify) g_object_unref), NULL);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	g_static_rec_mutex_free (&self->priv->__lock_blocks);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	G_OBJECT_CLASS (libvoxelcore_voxel_model_raster_layer_parent_class)->finalize (obj);
#line 972 "raster_layer.c"
}


GType libvoxelcore_voxel_model_raster_layer_get_type (void) {
	static volatile gsize libvoxelcore_voxel_model_raster_layer_type_id__volatile = 0;
	if (g_once_init_enter (&libvoxelcore_voxel_model_raster_layer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (libvoxelcorevoxel_modelRasterLayerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) libvoxelcore_voxel_model_raster_layer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (libvoxelcorevoxel_modelRasterLayer), 0, (GInstanceInitFunc) libvoxelcore_voxel_model_raster_layer_instance_init, NULL };
		static const GInterfaceInfo libvoxelcore_voxel_model_raster_layer_kind_info = { (GInterfaceInitFunc) libvoxelcore_voxel_model_raster_layer_libvoxelcore_voxel_model_raster_layer_kind_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType libvoxelcore_voxel_model_raster_layer_type_id;
		libvoxelcore_voxel_model_raster_layer_type_id = g_type_register_static (G_TYPE_OBJECT, "libvoxelcorevoxel_modelRasterLayer", &g_define_type_info, 0);
		g_type_add_interface_static (libvoxelcore_voxel_model_raster_layer_type_id, LIBVOXELCORE_VOXEL_MODEL_TYPE_RASTER_LAYER_KIND, &libvoxelcore_voxel_model_raster_layer_kind_info);
		g_once_init_leave (&libvoxelcore_voxel_model_raster_layer_type_id__volatile, libvoxelcore_voxel_model_raster_layer_type_id);
	}
	return libvoxelcore_voxel_model_raster_layer_type_id__volatile;
}


static void _vala_libvoxelcore_voxel_model_raster_layer_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	libvoxelcorevoxel_modelRasterLayer * self;
	self = LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER (object);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	switch (property_id) {
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		case LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_CENTER_X:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		g_value_set_int (value, libvoxelcore_voxel_model_raster_layer_get_center_x (self));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		case LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_CENTER_Y:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		g_value_set_int (value, libvoxelcore_voxel_model_raster_layer_get_center_y (self));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		case LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_WIDTH:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		g_value_set_int (value, libvoxelcore_voxel_model_raster_layer_get_width (self));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		case LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_LENGTH:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		g_value_set_int (value, libvoxelcore_voxel_model_raster_layer_get_length (self));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		case LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_BLOCK_SIZE:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		g_value_set_int (value, libvoxelcore_voxel_model_raster_layer_get_block_size (self));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 1025 "raster_layer.c"
		default:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 1031 "raster_layer.c"
	}
}


static void _vala_libvoxelcore_voxel_model_raster_layer_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	libvoxelcorevoxel_modelRasterLayer * self;
	self = LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER (object);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
	switch (property_id) {
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		case LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_CENTER_X:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		libvoxelcore_voxel_model_raster_layer_set_center_x (self, g_value_get_int (value));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		case LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_CENTER_Y:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		libvoxelcore_voxel_model_raster_layer_set_center_y (self, g_value_get_int (value));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		case LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_WIDTH:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		libvoxelcore_voxel_model_raster_layer_set_width (self, g_value_get_int (value));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		case LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_LENGTH:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		libvoxelcore_voxel_model_raster_layer_set_length (self, g_value_get_int (value));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		case LIBVOXELCORE_VOXEL_MODEL_RASTER_LAYER_BLOCK_SIZE:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		libvoxelcore_voxel_model_raster_layer_set_block_size (self, g_value_get_int (value));
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 1071 "raster_layer.c"
		default:
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/raster_layer.vala"
		break;
#line 1077 "raster_layer.c"
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



