/* voxel.c generated by valac 0.16.1, the Vala compiler
 * generated from voxel.vala, do not modify */

/*

  This file is part of VoxelPress.

  VoxelPress is free software: you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  VoxelPress is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with VoxelPress.  If not, see <http://www.gnu.org/licenses/>.

  Have a nice day!

*/

#include <glib.h>
#include <glib-object.h>


#define LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND (libvoxelcore_voxel_model_voxel_kind_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND, libvoxelcorevoxel_modelVoxelKind))
#define LIBVOXELCORE_VOXEL_MODEL_IS_VOXEL_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND))
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND, libvoxelcorevoxel_modelVoxelKindIface))

typedef struct _libvoxelcorevoxel_modelVoxelKind libvoxelcorevoxel_modelVoxelKind;
typedef struct _libvoxelcorevoxel_modelVoxelKindIface libvoxelcorevoxel_modelVoxelKindIface;

#define LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND (libvoxelcore_materials_material_kind_get_type ())
#define LIBVOXELCORE_MATERIALS_MATERIAL_KIND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND, libvoxelcorematerialsMaterialKind))
#define LIBVOXELCORE_MATERIALS_IS_MATERIAL_KIND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND))
#define LIBVOXELCORE_MATERIALS_MATERIAL_KIND_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND, libvoxelcorematerialsMaterialKindIface))

typedef struct _libvoxelcorematerialsMaterialKind libvoxelcorematerialsMaterialKind;
typedef struct _libvoxelcorematerialsMaterialKindIface libvoxelcorematerialsMaterialKindIface;

#define LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL (libvoxelcore_voxel_model_voxel_get_type ())
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL, libvoxelcorevoxel_modelVoxel))
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL, libvoxelcorevoxel_modelVoxelClass))
#define LIBVOXELCORE_VOXEL_MODEL_IS_VOXEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL))
#define LIBVOXELCORE_VOXEL_MODEL_IS_VOXEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL))
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL, libvoxelcorevoxel_modelVoxelClass))

typedef struct _libvoxelcorevoxel_modelVoxel libvoxelcorevoxel_modelVoxel;
typedef struct _libvoxelcorevoxel_modelVoxelClass libvoxelcorevoxel_modelVoxelClass;
typedef struct _libvoxelcorevoxel_modelVoxelPrivate libvoxelcorevoxel_modelVoxelPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _libvoxelcorematerialsMaterialKindIface {
	GTypeInterface parent_iface;
};

struct _libvoxelcorevoxel_modelVoxelKindIface {
	GTypeInterface parent_iface;
	libvoxelcorematerialsMaterialKind* (*get_material) (libvoxelcorevoxel_modelVoxelKind* self);
	void (*set_material) (libvoxelcorevoxel_modelVoxelKind* self, libvoxelcorematerialsMaterialKind* value);
};

struct _libvoxelcorevoxel_modelVoxel {
	GObject parent_instance;
	libvoxelcorevoxel_modelVoxelPrivate * priv;
};

struct _libvoxelcorevoxel_modelVoxelClass {
	GObjectClass parent_class;
};

struct _libvoxelcorevoxel_modelVoxelPrivate {
	libvoxelcorematerialsMaterialKind* _material;
};


static gpointer libvoxelcore_voxel_model_voxel_parent_class = NULL;
static libvoxelcorevoxel_modelVoxelKindIface* libvoxelcore_voxel_model_voxel_libvoxelcore_voxel_model_voxel_kind_parent_iface = NULL;

GType libvoxelcore_materials_material_kind_get_type (void) G_GNUC_CONST;
GType libvoxelcore_voxel_model_voxel_kind_get_type (void) G_GNUC_CONST;
GType libvoxelcore_voxel_model_voxel_get_type (void) G_GNUC_CONST;
#define LIBVOXELCORE_VOXEL_MODEL_VOXEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL, libvoxelcorevoxel_modelVoxelPrivate))
enum  {
	LIBVOXELCORE_VOXEL_MODEL_VOXEL_DUMMY_PROPERTY,
	LIBVOXELCORE_VOXEL_MODEL_VOXEL_MATERIAL
};
libvoxelcorevoxel_modelVoxel* libvoxelcore_voxel_model_voxel_new (void);
libvoxelcorevoxel_modelVoxel* libvoxelcore_voxel_model_voxel_construct (GType object_type);
static void libvoxelcore_voxel_model_voxel_finalize (GObject* obj);
libvoxelcorematerialsMaterialKind* libvoxelcore_voxel_model_voxel_kind_get_material (libvoxelcorevoxel_modelVoxelKind* self);
static void _vala_libvoxelcore_voxel_model_voxel_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
void libvoxelcore_voxel_model_voxel_kind_set_material (libvoxelcorevoxel_modelVoxelKind* self, libvoxelcorematerialsMaterialKind* value);
static void _vala_libvoxelcore_voxel_model_voxel_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


libvoxelcorevoxel_modelVoxel* libvoxelcore_voxel_model_voxel_construct (GType object_type) {
	libvoxelcorevoxel_modelVoxel * self = NULL;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	self = (libvoxelcorevoxel_modelVoxel*) g_object_new (object_type, NULL);
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	return self;
#line 108 "voxel.c"
}


libvoxelcorevoxel_modelVoxel* libvoxelcore_voxel_model_voxel_new (void) {
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	return libvoxelcore_voxel_model_voxel_construct (LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL);
#line 115 "voxel.c"
}


static libvoxelcorematerialsMaterialKind* libvoxelcore_voxel_model_voxel_real_get_material (libvoxelcorevoxel_modelVoxelKind* base) {
	libvoxelcorematerialsMaterialKind* result;
	libvoxelcorevoxel_modelVoxel* self;
	libvoxelcorematerialsMaterialKind* _tmp0_;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	self = (libvoxelcorevoxel_modelVoxel*) base;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	_tmp0_ = self->priv->_material;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	result = _tmp0_;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	return result;
#line 131 "voxel.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	return self ? g_object_ref (self) : NULL;
#line 138 "voxel.c"
}


static void libvoxelcore_voxel_model_voxel_real_set_material (libvoxelcorevoxel_modelVoxelKind* base, libvoxelcorematerialsMaterialKind* value) {
	libvoxelcorevoxel_modelVoxel* self;
	libvoxelcorematerialsMaterialKind* _tmp0_;
	libvoxelcorematerialsMaterialKind* _tmp1_;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	self = (libvoxelcorevoxel_modelVoxel*) base;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	_tmp0_ = value;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	_g_object_unref0 (self->priv->_material);
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	self->priv->_material = _tmp1_;
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	g_object_notify ((GObject *) self, "material");
#line 158 "voxel.c"
}


static void libvoxelcore_voxel_model_voxel_class_init (libvoxelcorevoxel_modelVoxelClass * klass) {
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	libvoxelcore_voxel_model_voxel_parent_class = g_type_class_peek_parent (klass);
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	g_type_class_add_private (klass, sizeof (libvoxelcorevoxel_modelVoxelPrivate));
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_libvoxelcore_voxel_model_voxel_get_property;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_libvoxelcore_voxel_model_voxel_set_property;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	G_OBJECT_CLASS (klass)->finalize = libvoxelcore_voxel_model_voxel_finalize;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), LIBVOXELCORE_VOXEL_MODEL_VOXEL_MATERIAL, g_param_spec_object ("material", "material", "material", LIBVOXELCORE_MATERIALS_TYPE_MATERIAL_KIND, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 175 "voxel.c"
}


static void libvoxelcore_voxel_model_voxel_libvoxelcore_voxel_model_voxel_kind_interface_init (libvoxelcorevoxel_modelVoxelKindIface * iface) {
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	libvoxelcore_voxel_model_voxel_libvoxelcore_voxel_model_voxel_kind_parent_iface = g_type_interface_peek_parent (iface);
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	iface->get_material = libvoxelcore_voxel_model_voxel_real_get_material;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	iface->set_material = libvoxelcore_voxel_model_voxel_real_set_material;
#line 186 "voxel.c"
}


static void libvoxelcore_voxel_model_voxel_instance_init (libvoxelcorevoxel_modelVoxel * self) {
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	self->priv = LIBVOXELCORE_VOXEL_MODEL_VOXEL_GET_PRIVATE (self);
#line 193 "voxel.c"
}


static void libvoxelcore_voxel_model_voxel_finalize (GObject* obj) {
	libvoxelcorevoxel_modelVoxel * self;
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	self = LIBVOXELCORE_VOXEL_MODEL_VOXEL (obj);
#line 30 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	_g_object_unref0 (self->priv->_material);
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	G_OBJECT_CLASS (libvoxelcore_voxel_model_voxel_parent_class)->finalize (obj);
#line 205 "voxel.c"
}


GType libvoxelcore_voxel_model_voxel_get_type (void) {
	static volatile gsize libvoxelcore_voxel_model_voxel_type_id__volatile = 0;
	if (g_once_init_enter (&libvoxelcore_voxel_model_voxel_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (libvoxelcorevoxel_modelVoxelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) libvoxelcore_voxel_model_voxel_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (libvoxelcorevoxel_modelVoxel), 0, (GInstanceInitFunc) libvoxelcore_voxel_model_voxel_instance_init, NULL };
		static const GInterfaceInfo libvoxelcore_voxel_model_voxel_kind_info = { (GInterfaceInitFunc) libvoxelcore_voxel_model_voxel_libvoxelcore_voxel_model_voxel_kind_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType libvoxelcore_voxel_model_voxel_type_id;
		libvoxelcore_voxel_model_voxel_type_id = g_type_register_static (G_TYPE_OBJECT, "libvoxelcorevoxel_modelVoxel", &g_define_type_info, 0);
		g_type_add_interface_static (libvoxelcore_voxel_model_voxel_type_id, LIBVOXELCORE_VOXEL_MODEL_TYPE_VOXEL_KIND, &libvoxelcore_voxel_model_voxel_kind_info);
		g_once_init_leave (&libvoxelcore_voxel_model_voxel_type_id__volatile, libvoxelcore_voxel_model_voxel_type_id);
	}
	return libvoxelcore_voxel_model_voxel_type_id__volatile;
}


static void _vala_libvoxelcore_voxel_model_voxel_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	libvoxelcorevoxel_modelVoxel * self;
	self = LIBVOXELCORE_VOXEL_MODEL_VOXEL (object);
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	switch (property_id) {
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
		case LIBVOXELCORE_VOXEL_MODEL_VOXEL_MATERIAL:
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
		g_value_set_object (value, libvoxelcore_voxel_model_voxel_kind_get_material ((libvoxelcorevoxel_modelVoxelKind*) self));
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
		break;
#line 234 "voxel.c"
		default:
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
		break;
#line 240 "voxel.c"
	}
}


static void _vala_libvoxelcore_voxel_model_voxel_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	libvoxelcorevoxel_modelVoxel * self;
	self = LIBVOXELCORE_VOXEL_MODEL_VOXEL (object);
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
	switch (property_id) {
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
		case LIBVOXELCORE_VOXEL_MODEL_VOXEL_MATERIAL:
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
		libvoxelcore_voxel_model_voxel_kind_set_material ((libvoxelcorevoxel_modelVoxelKind*) self, g_value_get_object (value));
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
		break;
#line 256 "voxel.c"
		default:
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 29 "/home/aeva/science/voxelpress/libvoxelcore/voxel_models/voxel.vala"
		break;
#line 262 "voxel.c"
	}
}



